# Numpy

In [2]:
import numpy as np


In [2]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [5]:
print(dir(np),end="")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [12]:
a = np.array([1,2,3])
print(a,type(a))
print(a.dtype)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.ndim)


[1 2 3] <class 'numpy.ndarray'>
int32
(3,)
3
4
1


In [13]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
a = np.array(range(15))


In [17]:
print(a)

[  1.   234.    56.     4.44]


In [16]:
a = np.array([1,234,56,4.44])
print(a,type(a))

[  1.   234.    56.     4.44] <class 'numpy.ndarray'>


In [18]:
a = np.array([1,2,388.22])
print(a,type(a))
print(a.dtype)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.ndim)


[  1.     2.   388.22] <class 'numpy.ndarray'>
float64
(3,)
3
8
1


In [29]:
a = np.array(range(16))
print(a,type(a))

print()

a = np.array([1,2,3,4,5.6],dtype="int32",ndmin=2)
print(a,type(a))
print('itemsize', a.itemsize,a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <class 'numpy.ndarray'>

[[1 2 3 4 5]] <class 'numpy.ndarray'>
itemsize 4 (1, 5)


In [39]:
a =np.arange(10,22)
print(a)
a.reshape(3,4)

[10 11 12 13 14 15 16 17 18 19 20 21]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [45]:
a = np.arange(10,19,2)
print(a,a.min(),a.max(),a.sum())
print(a,a.mean())

[10 12 14 16 18] 10 18 70
[10 12 14 16 18] 14.0


In [47]:
a =np.array([[1,2],[2,3]])

In [48]:
a

array([[1, 2],
       [2, 3]])

In [52]:
a =np.arange(0,24).reshape(4,6)

In [53]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [54]:
a.min()

0

In [55]:
a.max()

23

In [56]:
a.mean()

11.5

In [3]:
a =np.arange(0,24).reshape(4,6)
print(a)
print(a.min(), a.max())
print(a.min(axis =0), a.max(axis=0))# axis = 1: columns
print(a.min(axis =1), a.max(axis=1))# axis = 0:rows 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
0 23
[0 1 2 3 4 5] [18 19 20 21 22 23]
[ 0  6 12 18] [ 5 11 17 23]


In [4]:
## unit( only postive integer) consight int

In [63]:
a =np.arange(0,24,dtype="i8").reshape(4,6)
print(a)
print(a.min(), a.max())
print(a.min(axis =0), a.max(axis=0))# axis = 0: columns
print(a.min(axis =1), a.max(axis=1))# axis = 1:rows 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
0 23
[0 1 2 3 4 5] [18 19 20 21 22 23]
[ 0  6 12 18] [ 5 11 17 23]


In [65]:
np.random.randint(10,20,100).reshape(10,10)

array([[13, 15, 16, 19, 18, 19, 12, 13, 13, 12],
       [11, 16, 17, 15, 11, 18, 19, 15, 11, 13],
       [17, 18, 18, 15, 19, 14, 19, 18, 18, 14],
       [16, 14, 19, 12, 19, 15, 11, 14, 12, 15],
       [10, 10, 18, 18, 18, 17, 11, 14, 10, 13],
       [18, 15, 16, 16, 13, 16, 11, 19, 17, 11],
       [11, 19, 18, 11, 10, 12, 12, 11, 17, 13],
       [18, 19, 11, 14, 17, 15, 13, 15, 14, 15],
       [15, 18, 11, 18, 18, 10, 17, 10, 16, 19],
       [13, 16, 11, 11, 12, 15, 14, 17, 18, 12]])

In [81]:
a= np.arange(10,100,10)
print(a)
a.resize(2,4)
print(a)
a.resize(20)
print(a)

[10 20 30 40 50 60 70 80 90]
[[10 20 30 40]
 [50 60 70 80]]
[10 20 30 40 50 60 70 80  0  0  0  0  0  0  0  0  0  0  0  0]



# indexing and slicing

In [97]:
a = np.arange(12).reshape(4,3)
print(a)

print(a[1,0])
print(a[1:4])
print(a[1:4,1:])

print(np.linspace(10,20,20,dtype ="int8"))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 20]


In [110]:
a = np.arange(12).reshape(4,3)
print(a)
print()
print(a[(0,2)])
#       row,column
print(a[(0,2),(1,2)])
#      [(row),row),(colum,(column)]
#         0            1
#              2               2

print()
print(a[:,(1,2)])

print()
print(a[(True,False,True,False),])


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2
[1 8]

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]]

[[0 1 2]
 [6 7 8]]


In [121]:
a = np.arange(10,20)
a2 = np.arange(20,10,-1)
print(a,a2)
print(a*a2)
print(a*2)

print()
print()
x = (a%2==0)
print(x)

print()
print()

y = (a%3==0)| (a%5==0)
print(y)
print(a[y])
print()
print()

z = (a%3==0) & (a%5==0)
print(z)
print(a[z])

[10 11 12 13 14 15 16 17 18 19] [20 19 18 17 16 15 14 13 12 11]
[200 209 216 221 224 225 224 221 216 209]
[20 22 24 26 28 30 32 34 36 38]


[ True False  True False  True False  True False  True False]


[ True False  True False False  True False False  True False]
[10 12 15 18]


[False False False False False  True False False False False]
[15]


In [123]:
print(np.nan>0)
print(np.nan<0)
print(np.nan==0)
print(np.nan==np.nan)


False
False
False
False


In [124]:
print(np.array([10,10,np.nan]))

[10. 10. nan]


In [126]:
print(sum(np.array([10,10,np.nan])))

nan


In [7]:
a = np.arange(10,20,dtype = np.float64)
a[3] = np.nan
print(a)
print()
print()
y = (a%3==0)| (a%5==0)
print(y)
print(np.where(y))
print()

print(a[y])
print()

print(y.any())
print()

print(y.all())
print()

print(np.isnan(a))

[10. 11. 12. nan 14. 15. 16. 17. 18. 19.]


[ True False  True False False  True False False  True False]
(array([0, 2, 5, 8], dtype=int64),)

[10. 12. 15. 18.]

True

False

[False False False  True False False False False False False]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in remainder
  
